### ISSUE TITLE
tcp and kcp protocol

### ISSUE THREAD

**Issue by wandou2018** [n-hop/oasis#33]

**Comment by wandou2018** [comment]
For the kcp protocol, he needs to know which is the client and which is the server.  
The two use different binaries and have different running parameters.

**Comment by penglei0** [comment]
> For the kcp protocol, he needs to know which is the client and which is the server. The two use different binaries and have different running parameters.

use config.client_host? config.server_host?

**Comment by wandou2018** [comment]
> > For the kcp protocol, he needs to know which is the client and which is the server. The two use different binaries and have different running parameters.
> 
> use config.client_host? config.server_host?

```
test_iperf.py  
def _run_test(self, network: INetwork, proto: IProtoInfo):
      proto.set_xxx(config.client_host? config.server_host)
      xx
      return self._run_iperf
```

**Comment by penglei0** [comment]
> > > For the kcp protocol, he needs to know which is the client and which is the server. The two use different binaries and have different running parameters.
> > 
> > 
> > use config.client_host? config.server_host?
> 
> ```
> test_iperf.py  
> def _run_test(self, network: INetwork, proto: IProtoInfo):
>       proto.set_xxx(config.client_host? config.server_host)
>       xx
>       return self._run_iperf
> ```

```python
kcp1 = KCPProtocol(client_config)
kcp2 = KCPProtocol(server_config)
client_server_mode= CSProtocol(kcp1,kcp2)

class CSProtocol(IProtoSuite):
  def run:
     kcp1.run() # start client
     kcp2.run() # start server
```

**Comment by wandou2018** [comment]
> > > > For the kcp protocol, he needs to know which is the client and which is the server. The two use different binaries and have different running parameters.
> > > 
> > > 
> > > use config.client_host? config.server_host?
> > 
> > 
> > ```
> > test_iperf.py  
> > def _run_test(self, network: INetwork, proto: IProtoInfo):
> >       proto.set_xxx(config.client_host? config.server_host)
> >       xx
> >       return self._run_iperf
> > ```
> 
> ```python
> kcp1 = KCPProtocol(client_config)
> kcp2 = KCPProtocol(server_config)
> client_server_mode= CSProtocol(kcp1,kcp2)
> client_server_mode.run()
>  .....
> 
> class CSProtocol(IProtoSuite):
>   def __init(client: IProtoSuite, server:IProtoSuite)
>      pass
>   def run():
>      kcp1.run() # start client
>      kcp2.run() # start server
> ```

There is no 'config.client_host' and 'config.server_host' information, which is contained in test_suites

**Comment by penglei0** [comment]
> > > > > For the kcp protocol, he needs to know which is the client and which is the server. The two use different binaries and have different running parameters.
> > > > 
> > > > 
> > > > use config.client_host? config.server_host?
> > > 
> > > 
> > > ```
> > > test_iperf.py  
> > > def _run_test(self, network: INetwork, proto: IProtoInfo):
> > >       proto.set_xxx(config.client_host? config.server_host)
> > >       xx
> > >       return self._run_iperf
> > > ```
> > 
> > 
> > ```python
> > kcp1 = KCPProtocol(client_config)
> > kcp2 = KCPProtocol(server_config)
> > client_server_mode= CSProtocol(kcp1,kcp2)
> > client_server_mode.run()
> >  .....
> > 
> > class CSProtocol(IProtoSuite):
> >   def __init(client: IProtoSuite, server:IProtoSuite)
> >      pass
> >   def run():
> >      kcp1.run() # start client
> >      kcp2.run() # start server
> > ```
> 
> There is no 'config.client_host' and 'config.server_host' information, which is contained in test_suites


```
client_config.host = [0]
kcp1 = KCPProtocol(client_config)
server_config.host = [6]
kcp2 = KCPProtocol(server_config)
```

**Comment by penglei0** [comment]
> > > > > For the kcp protocol, he needs to know which is the client and which is the server. The two use different binaries and have different running parameters.
> > > > 
> > > > 
> > > > use config.client_host? config.server_host?
> > > 
> > > 
> > > ```
> > > test_iperf.py  
> > > def _run_test(self, network: INetwork, proto: IProtoInfo):
> > >       proto.set_xxx(config.client_host? config.server_host)
> > >       xx
> > >       return self._run_iperf
> > > ```
> > 
> > 
> > ```python
> > kcp1 = KCPProtocol(client_config)
> > kcp2 = KCPProtocol(server_config)
> > client_server_mode= CSProtocol(kcp1,kcp2)
> > client_server_mode.run()
> >  .....
> > 
> > class CSProtocol(IProtoSuite):
> >   def __init(client: IProtoSuite, server:IProtoSuite)
> >      pass
> >   def run():
> >      kcp1.run() # start client
> >      kcp2.run() # start server
> > ```
> 
> There is no 'config.client_host' and 'config.server_host' information, which is contained in test_suites
#

```
client_config.hosts= [0]
kcp1 = KCPProtocol(client_config)
server_config.hosts= [6]
kcp2 = KCPProtocol(server_config)
```
